In [1]:
import numpy as np

In [2]:
arreglo_once_cuadrado = np.arange(11)**2

In [3]:
print(arreglo_once_cuadrado)

[  0   1   4   9  16  25  36  49  64  81 100]


In [6]:
arreglo_once_cuadrado[:-6]

array([ 0,  1,  4,  9, 16])

In [10]:
arreglo_once_cuadrado[2:4]

array([4, 9])

In [7]:
arreglo_once_cuadrado[:-6]

array([ 0,  1,  4,  9, 16])

In [8]:
arreglo_once_cuadrado[::-1]

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0])

In [9]:
for numero in arreglo_once_cuadrado[::-1]:
    print(numero)

100
81
64
49
36
25
16
9
4
1
0
