In [1]:
import numpy as np

In [3]:
paises_uno = ('Ecuador', 'USA', 'Cuba', 'Venezuela')
paises_dos = ('Brazil', 'China', 'Japon', 'Mexico')

In [5]:
arreglo_paises_2d=np.array([paises_uno, paises_dos])

In [6]:
arreglo_paises_2d

array([['Ecuador', 'USA', 'Cuba', 'Venezuela'],
       ['Brazil', 'China', 'Japon', 'Mexico']], dtype='<U9')

In [7]:
arreglo_paises_2d.shape

(2, 4)

In [8]:
arreglo_paises_2d.flatten()

array(['Ecuador', 'USA', 'Cuba', 'Venezuela', 'Brazil', 'China', 'Japon',
       'Mexico'], dtype='<U9')

In [10]:
arreglo_paises_2d.flatten().shape

(8,)

In [11]:
arreglo_paises_2d.flatten().reshape(2,2,2)

array([[['Ecuador', 'USA'],
        ['Cuba', 'Venezuela']],

       [['Brazil', 'China'],
        ['Japon', 'Mexico']]], dtype='<U9')

In [12]:
arreglo_paises_2d.flatten().reshape(4,-1)

array([['Ecuador', 'USA'],
       ['Cuba', 'Venezuela'],
       ['Brazil', 'China'],
       ['Japon', 'Mexico']], dtype='<U9')

In [13]:
arreglo_paises_2d.T

array([['Ecuador', 'Brazil'],
       ['USA', 'China'],
       ['Cuba', 'Japon'],
       ['Venezuela', 'Mexico']], dtype='<U9')

In [14]:
arreglo_paises_2d.shape

(2, 4)

In [16]:
arreglo = np.arange(12)
arreglo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
np.split(arreglo, 4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [18]:
np.split(arreglo, [1,3,5,7,8])

[array([0]),
 array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7]),
 array([ 8,  9, 10, 11])]

In [19]:
arreglo_paises=arreglo_paises_2d.flatten()

In [20]:
np.hsplit(arreglo_paises_2d, 2)


[array([['Ecuador', 'USA'],
        ['Brazil', 'China']], dtype='<U9'), array([['Cuba', 'Venezuela'],
        ['Japon', 'Mexico']], dtype='<U9')]

In [21]:
np.vsplit(arreglo_paises_2d, 2)

[array([['Ecuador', 'USA', 'Cuba', 'Venezuela']], dtype='<U9'),
 array([['Brazil', 'China', 'Japon', 'Mexico']], dtype='<U9')]

In [22]:
arr1, arr2, arr3, arr4 = np.hsplit(arreglo_paises_2d, 4)

In [23]:
type(np.hsplit(arreglo_paises_2d, 4))

list

In [25]:
arr1
arr2
arr3
arr4

array([['Venezuela'],
       ['Mexico']], dtype='<U9')