In [2]:
import numpy as np

In [3]:
numeros=np.arange(11)**2
numeros

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [4]:
indices=[2,5,7]

In [5]:
numeros[indices]

array([ 4, 25, 49])

In [6]:
arreglo_de_frutas=np.array([
    ["pinia", "manzana", "pera", "melon"],
    ["pera", "uva", "naranja", "papaya"],
    ["frutilla", "platano", "granadilla", "sandia"]
])
arreglo_de_frutas.shape

(3, 4)

In [7]:
arreglo_filas=np.array([
    [0,0],
    [1,1],
    [2,2]
])
arreglo_columnas=np.array([
    [1,3],
    [1,2],
    [0,2]
])
arreglo_filas
arreglo_columnas

array([[1, 3],
       [1, 2],
       [0, 2]])

In [8]:
arreglo_de_frutas[arreglo_filas,arreglo_columnas]

array([['manzana', 'melon'],
       ['uva', 'naranja'],
       ['frutilla', 'granadilla']], dtype='<U10')

In [9]:
arreglo_de_frutas

array([['pinia', 'manzana', 'pera', 'melon'],
       ['pera', 'uva', 'naranja', 'papaya'],
       ['frutilla', 'platano', 'granadilla', 'sandia']], dtype='<U10')

In [10]:
arreglo_filas_2=np.array([
    [0,0],
    [1,1],
    [2,2]
])
arreglo_columnas_2=np.array([
    [2,3],
    [2,3],
    [2,3]
])
arreglo_filas
arreglo_columnas

array([[1, 3],
       [1, 2],
       [0, 2]])

In [11]:
arreglo_de_frutas[arreglo_filas_2,arreglo_columnas_2]

array([['pera', 'melon'],
       ['naranja', 'papaya'],
       ['granadilla', 'sandia']], dtype='<U10')

In [12]:
arreglo_de_frutas_2=np.array([
    [
        ["pinia", "manzana"],
        ["pera", "melon"],
        ["kiwi", "uva"],
    ],
    [    
        ["naranja", "papaya"],
        ["frutilla", "platano"],
        ["granadilla", "sandia"]
    ],
    [
        ["pinia_2", "manzana_2"],
        ["pera_2", "melon_2"],
        ["kiwi_2", "uva_2"],
    ],
    [    
        ["naranja_2", "papaya_2"],
        ["frutilla_2", "platano_2"],
        ["granadilla_2", "sandia_2"]
    ]])
arreglo_de_frutas_2.shape

(4, 3, 2)

In [13]:
arreglo_de_frutas_2

array([[['pinia', 'manzana'],
        ['pera', 'melon'],
        ['kiwi', 'uva']],

       [['naranja', 'papaya'],
        ['frutilla', 'platano'],
        ['granadilla', 'sandia']],

       [['pinia_2', 'manzana_2'],
        ['pera_2', 'melon_2'],
        ['kiwi_2', 'uva_2']],

       [['naranja_2', 'papaya_2'],
        ['frutilla_2', 'platano_2'],
        ['granadilla_2', 'sandia_2']]], dtype='<U12')

In [14]:
arreglo_filas_3=np.array([
    [0,0],
])
arreglo_columnas_3=np.array([
    [0,1],
])
arreglo_fondo_3=np.array([0,1])
arreglo_de_frutas_2[arreglo_filas_3, arreglo_columnas_3,arreglo_fondo_3 ]

array([['pinia', 'melon']], dtype='<U12')

In [15]:
arreglo_de_frutas_2[[[0,0],[0,0]],[[0,0],[0,1]],[0,1]]

array([['pinia', 'manzana'],
       ['pinia', 'melon']], dtype='<U12')

In [16]:
arreglo_de_frutas_2

array([[['pinia', 'manzana'],
        ['pera', 'melon'],
        ['kiwi', 'uva']],

       [['naranja', 'papaya'],
        ['frutilla', 'platano'],
        ['granadilla', 'sandia']],

       [['pinia_2', 'manzana_2'],
        ['pera_2', 'melon_2'],
        ['kiwi_2', 'uva_2']],

       [['naranja_2', 'papaya_2'],
        ['frutilla_2', 'platano_2'],
        ['granadilla_2', 'sandia_2']]], dtype='<U12')

In [20]:
condicion=np.array(["pinia", "manzana", "pera", "melon"])
funcion=lambda string : "p" in string
seleccion=condicion[(lambda string : "p" in string)]
seleccion

NameError: name 'sd' is not defined

In [ ]:
lambda string : "p" in string