In [1]:
import numpy as np

## Resolucion de Ecuaciones lineares

In [2]:
variables_1=np.array([[2,3],[3,4]])
valores_1=np.array([-1,0])
print(f"array: {variables_1}")
print(f"valores: {valores_1}")
resolucion=np.linalg.solve(variables_1, valores_1)
print(f"soluciones: {resolucion}")

array: [[2 3]
 [3 4]]
valores: [-1  0]
soluciones: [ 4. -3.]


In [3]:
variables_2=np.random.randint(1,30,[4,4])
variables_2

array([[14, 22, 28, 20],
       [12,  1,  6,  5],
       [16,  1, 29, 29],
       [ 2, 15, 20, 10]])

In [4]:
valores_2=np.random.randint(1,30,4)
valores_2

array([ 8, 24, 14, 25])

In [5]:
resolucion_2=np.linalg.solve(variables_2, valores_2)
resolucion_2

array([ 1.8425986 , -2.96697671,  7.01348331, -7.44502127])

## Resolucion de Ecuaciones lineares

In [6]:
numeros_1=np.random.randint(1,30,[4,4])
numeros_2=np.random.randint(1,30,[4,4])
print(numeros_1)
print("---------------------------------")
print(numeros_2)
print("---------------------------------")
print(numeros_1*numeros_2)
print("---------------------------------")
print(numeros_1*3)
print("---------------------------------")
print(numeros_1/numeros_2)

[[29 10 13  7]
 [16 16  4 25]
 [22 17 28 15]
 [ 6 14  9  3]]
---------------------------------
[[29  1 27 10]
 [ 3  2 12  9]
 [ 8 24  5 17]
 [ 2 29 14 24]]
---------------------------------
[[841  10 351  70]
 [ 48  32  48 225]
 [176 408 140 255]
 [ 12 406 126  72]]
---------------------------------
[[87 30 39 21]
 [48 48 12 75]
 [66 51 84 45]
 [18 42 27  9]]
---------------------------------
[[ 1.         10.          0.48148148  0.7       ]
 [ 5.33333333  8.          0.33333333  2.77777778]
 [ 2.75        0.70833333  5.6         0.88235294]
 [ 3.          0.48275862  0.64285714  0.125     ]]


## Ordenar matriz

In [7]:
numeros_1=np.random.randint(1,30,[4,4])
print(numeros_1)
print("---------------------------------")
print(np.sort(numeros_1))
print("---------------------------------")
ordenada=np.sort(numeros_1.flatten()).reshape(4,4)
print(ordenada)

[[14 29  2  7]
 [12  9 17 26]
 [20 27 12 21]
 [26  2 25 14]]
---------------------------------
[[ 2  7 14 29]
 [ 9 12 17 26]
 [12 20 21 27]
 [ 2 14 25 26]]
---------------------------------
[[ 2  2  7  9]
 [12 12 14 14]
 [17 20 21 25]
 [26 26 27 29]]


In [9]:
print(ordenada.T)
print("---------------------------------")
alterna=np.arange(16).reshape(4,4)
for a in range(4):
    for b in range(4):
        alterna[a][b]=ordenada[3-a][3-b]
print(alterna)
print(ordenada.T*ordenada)

[[ 2 12 17 26]
 [ 2 12 20 26]
 [ 7 14 21 27]
 [ 9 14 25 29]]
---------------------------------
[[29 27 26 26]
 [25 21 20 17]
 [14 14 12 12]
 [ 9  7  2  2]]
[[  4  24 119 234]
 [ 24 144 280 364]
 [119 280 441 675]
 [234 364 675 841]]
